QLDETAI_11_2/QLDETAI/Models/BIEUMAU.cs
using System;
using System.Collections.Generic;

namespace QLDETAI.Models
{
    public partial class BIEUMAU
    {
        public int ID { get; set; }
        public Nullable<int> IDDETAI { get; set; }
        public string TENBIEUMAU { get; set; }
        public string LINKDOWN { get; set; }
        public virtual DETAI DETAI { get; set; }
    }
}

QLDETAI_11_2/QLDETAI/Controllers/RegisterController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Text;
using System.Threading.Tasks;
using System.IO;
using System.Data;
using System.Data.Entity;
using HtmlAgilityPack;
using System.Globalization;
using QLDETAI.Services;
using QLDETAI.Models;

namespace QLDETAI.Controllers
{
    public class RegisterController : Controller
    {
        DBHTTTHDContext db = new DBHTTTHDContext();
        //
        // GET: /Register/

        public ActionResult Index()
        {
            return View();
        }
        [AllowAnonymous]
        public ActionResult BasicLevel_R()
        {

            if (User.Identity.IsAuthenticated)
            {
                
                return View();
            }
            else
            {
                return RedirectToAction("Login", "Account");
            }
        }
        //private void XuLyUpload(string Title)
        //{
        //    if (Title != null)
        //    {
        //        if (Request.Files["file"].ContentLength > 0)
        //        {
        //            string extension = System.IO.Path.GetExtension(Request.Files["file"].FileName);
        //            string path1 = string.Format("{0}/{1}{2}", Server.MapPath("~/File"), Title, extension);
        //            if (System.IO.File.Exists(path1))
        //                System.IO.File.Delete(path1);
        //            DE_TAI detai = new DE_TAI();
        //            detai.LINK_FILE_THUYET_MINH_DE_TAI = path1;

        //            db.DE_TAI.Add(detai);
        //            db.SaveChanges();
        //            Request.Files["file"].SaveAs(path1);
        //            var query =
        //                        from dt in db.DE_TAI
        //                        where dt.LINK_FILE_THUYET_MINH_DE_TAI == path1
        //                        select dt;
        //            if (query != null)
        //            {
        //                CultureInfo myCIintl = new CultureInfo("vi-VN", false);     // Note new

        //                 Để bỏ vào database
        //                foreach (DE_TAI dt in query)
        //                {
        //                    SoKHCN_TMDT tmdt = new SoKHCN_TMDT(@"" + dt.LINK_FILE_THUYET_MINH_DE_TAI + "");
        //                    ViewBag.Success = "Success";
        //                    dt.TEN_DE_TAI = tmdt.tenDeTai;
        //                    ViewBag.TEN_DE_TAI = tmdt.tenDeTai;
        //                    dt.NGAY_BAT_DAU = tmdt.ngayBatDau;
        //                    ViewBag.NGAY_BAT_DAU = tmdt.ngayBatDau;
        //                    dt.NGAY_KET_THUC = tmdt.ngayKetThuc;
        //                    ViewBag.NGAY_KET_THUC = tmdt.ngayKetThuc;
        //                    dt.THOI_GIAN_THUC_HIEN = tmdt.thoiGianThucHien;
        //                    ViewBag.THOI_GIAN_THUC_HIEN = tmdt.thoiGianThucHien;
        //                    dt.KINH_PHI_THUC_HIEN = tmdt.kinhPhiThucHien;
        //                    ViewBag.KINH_PHI_THUC_HIEN = tmdt.kinhPhiThucHien;
        //                    dt.KINH_PHI_TU_NGAN_SACH_ = tmdt.kinhPhiTuNganSach;
        //                    ViewBag.KINH_PHI_TU_NGAN_SACH_ = tmdt.kinhPhiTuNganSach;
        //                    dt.KINH_PHI_TU_NGUON_KHAC = tmdt.kinhPhiTuNguonKhac;
        //                    ViewBag.KINH_PHI_TU_NGUON_KHAC = tmdt.kinhPhiTuNguonKhac;
        //                    dt.CONG_VAN = tmdt.congVan;
        //                    ViewBag.CONG_VAN = tmdt.congVan;
        //                    dt.MASO = tmdt.maDeTai;
        //                    ViewBag.MASO = tmdt.maDeTai;
        //                    db.Entry(dt).State = EntityState.Modified;
        //                }
        //                db.SaveChanges();
        //                 Bỏ vào form

        //            }
        //        }

        //    }
        //    Xử lý link và lưu vào csdl
        //}
        [AllowAnonymous]
        public ActionResult SoKHCNLevel_R(string Title)
        {
            if (User.Identity.IsAuthenticated)
            {
                List<SelectListItem> items = new List<SelectListItem>();
                items.Add(new SelectListItem { Text = "Thường", Value = "0", Selected = true });
                items.Add(new SelectListItem { Text = "Chủ nhiệm", Value = "1" });
                ViewBag.MemberType = items;
                //Code upload file
                //XuLyUpload(Title);
                //Xử lý link và lưu vào csdl

               
                return View();
            }
            else
            {
                return RedirectToAction("Login", "Account");
            }
        }

        [AllowAnonymous]
        public ActionResult ThuyetMinhDeTai()
        {
            return View();
        }
        [HttpPost]
        public ActionResult ThuyetMinhDeTai(string Title)
        {
            //XuLyUpload(Title);
            return View();
        }

        [AllowAnonymous]
        public ActionResult BieuMau()
        {
            return View();
        }
    }
}

QLDETAI_11_2/QLDETAI/Views/Register/BasicLevel_R.cshtml
@{
    ViewBag.Title = "BasicLevel_R";
}


<!-- jQuery -->
<script src="@Url.Content("~/Scripts/jquery.easing.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery-1.9.1.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/pre_next.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/js-func-nav.js")" type="text/javascript"></script>

<link href="~/Content/Site.css" rel="stylesheet" />

<div class="col_R">
    <h2>Cấp cơ sở</h2>
    <h3>Giới thiệu</h3>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer dictum, neque ut imperdiet pellentesque, nulla tellus tempus magna, sed consectetur orci metus a justo. Aliquam ac congue nunc. Mauris a tortor ut massa egestas tempus. Pellentesque tincidunt fermentum diam sagittis ullamcorper.</p>
    <h3>Gợi ý</h3>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer dictum, neque ut imperdiet pellentesque, nulla tellus tempus magna, sed consectetur orci metus a justo. Aliquam ac congue nunc. Mauris a tortor ut massa egestas tempus. Pellentesque tincidunt fermentum diam sagittis ullamcorper.</p>

</div>
<div class="col_R2" style="height:650px">
    <h2>Quy trình đăng ký</h2>
    <div class="breadcrumb flat">
        <a href="@Url.Action("BasicLevel_R", "Register")" class="active">Đề xuất</a>
        <a href="">Compare</a>
        <a href="">Order Confirmation</a>
        <a href="">Checkout</a>
    </div>
    <br />
    <br />
    <form id="msform">
        <!-- progressbar -->
        <ul id="progressbar" >
            <li class="active" style="width: 20%;">Account Setup</li>
            <li style="width: 20%;">Social Profiles</li>
            <li style="width: 20%;">Personal Details</li>
            <li style="width: 20%;">Personal Details2</li>
        </ul>
        <!-- fieldsets -->
        <fieldset>
            <h2 class="fs-title">Create your account</h2>
            <h3 class="fs-subtitle">This is step 1</h3>
            <input type="text" name="email" placeholder="Email" />
            <input type="password" name="pass" placeholder="Password" />
            <input type="password" name="cpass" placeholder="Confirm Password" />
            <input type="button" name="next" class="next action-button" value="Next" />
        </fieldset>
        <fieldset>
            <h2 class="fs-title">Social Profiles</h2>
            <h3 class="fs-subtitle">Your presence on the social network</h3>
            <input type="text" name="twitter" placeholder="Twitter" />
            <input type="text" name="facebook" placeholder="Facebook" />
            <input type="text" name="gplus" placeholder="Google Plus" />
            <input type="button" name="previous" class="previous action-button" value="Previous" />
            <input type="button" name="next" class="next action-button" value="Next" />
        </fieldset>
        <fieldset>
            <h2 class="fs-title">Social Profiles</h2>
            <h3 class="fs-subtitle">Your presence on the social network</h3>
            <input type="text" name="twitter" placeholder="Twitter" />
            <input type="text" name="facebook" placeholder="Facebook" />
            <input type="text" name="gplus" placeholder="Google Plus" />
            <input type="button" name="previous" class="previous action-button" value="Previous" />
            <input type="button" name="next" class="next action-button" value="Next" />
        </fieldset>
        <fieldset>
            <h2 class="fs-title">Personal Details</h2>
            <h3 class="fs-subtitle">We will never sell it</h3>
            <input type="text" name="fname" placeholder="First Name" />
            <input type="text" name="lname" placeholder="Last Name" />
            <input type="text" name="phone" placeholder="Phone" />
            <textarea name="address" placeholder="Address"></textarea>
            <input type="button" name="previous" class="previous action-button" value="Previous" />
            <input type="submit" name="submit" class="submit action-button" value="Submit" />
        </fieldset>
    </form>

</div>
<div class="cl">&nbsp;</div>

QLDETAI_11_2/QLDETAI/Views/Register/BieuMau.cshtml
@model QLDETAI.Models.ValidationModels
@{
    ViewBag.Title = "BasicLevel_R";
}


<!-- jQuery -->

<script src="@Url.Content("~/Scripts/pre_next.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>



<link href="~/Content/PSite.css" rel="stylesheet" />

<!-- -->
<script>

    $(document).ready(function () {
        $("#title_public").click(function () {
            $("#show_public").slideToggle("slow");
        });

        $("#title_private").click(function () {
            $("#show_private").slideToggle("slow");
        });
    });


</script>

<!-- -->

<!-- 
<div class="col_R">
    <h2>Cấp cơ sở</h2>
    <h3>Giới thiệu</h3>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer dictum, neque ut imperdiet pellentesque, nulla tellus tempus magna, sed consectetur orci metus a justo. Aliquam ac congue nunc. Mauris a tortor ut massa egestas tempus. Pellentesque tincidunt fermentum diam sagittis ullamcorper.</p>
    <h3>Gợi ý</h3>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer dictum, neque ut imperdiet pellentesque, nulla tellus tempus magna, sed consectetur orci metus a justo. Aliquam ac congue nunc. Mauris a tortor ut massa egestas tempus. Pellentesque tincidunt fermentum diam sagittis ullamcorper.</p>

</div>
-->
<div class="col_R2">
    <h2>Tiến trình thực hiện</h2>
    <div style="margin-left:40px"> <img src="~/Images/DangKy.jpg" style="width:100px; height:50px;"/> <p><b>Đăng ký đề tài</b></p></div>
    <br />
    <!-- progressbar -->
    <ul id="progressbar">
        <li class="active" style="width: 16%;">Lý lịch khoa học</li>
        <li class="active" style="width: 16%;">Thuyết minh đề tài</li>
        <li class="yet" style="width: 16%;">Export ra file để nộp</li>
    </ul>

    <br />
    <h2>Quy trình đăng ký Cấp sở KHCN</h2>
 
    <div class="breadcrumb flat">
        <a href="@Url.Action("SoKHCNLevel_R", "Register")">Lý lịch khoa học</a>
        <a href="@Url.Action("ThuyetMinhDeTai", "Register")">Thuyết minh đề tài</a>
        <a class="active" href="@Url.Action("BieuMau", "Register")">Download biểu mẫu để nộp</a>
    </div>
    <br />
    <br />
    <form id="msform">

        <fieldset id="tabs-7">
            <h2 class="fs-title">DOWNLOAD BIỂU MẪU ĐỂ NỘP</h2>
            <div>  
                <p><span style="font-size:25px;padding-left:20px">Hướng dẫn</span></p><br /><br />

                <p>
                <span class="line_span" style="padding-left:20px">---------------------------------------------------------------------------------------------------------------------------------------------------------------</span><br />
                <span class="line_span" style="padding-left:20px">---------------------------------------------------------------------------------------------------------------------------------------------------------------</span>
                </p><br />
                <p><span style="font-size:25px;padding-left:20px">Thực hiện</span></p><br /><br />
                <p id="msfile">
                     <span style="padding-left:50px">Export file cần nộp</span><br />
                    <input style="float:left;margin-top:10px" type="submit" id="btnSubmit" value="Export" />
                </p><br /><br />
            </div>
            
        </fieldset>
    </form>

</div>
<div class="cl">&nbsp;</div>