QLDETAI_11_2/QLDETAI/Controllers/GuideController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace QLDETAI.Controllers
{
    public class GuideController : Controller
    {
        //
        // GET: /Guide/

        public ActionResult Index()
        {
            return View();
        }
        public ActionResult BasicLevel()
        {
            return View();
        }
        public ActionResult BasicLevel_2()
        {
            return View();
        }
        public ActionResult BasicLevel_3()
        {
            return View();
        }
        public ActionResult BasicLevel_4()
        {
            return View();
        }
        public ActionResult CapTruong()
        {
            return View();
        }
        public ActionResult CapTruong_1()
        {
            return View();
        }
        public ActionResult CapTruong_2()
        {
            return View();
        }
        public ActionResult CapTruong_3()
        {
            return View();
        }
        public ActionResult DHQG_ABLevel()
        {
            return View();
        }
        public ActionResult DHQG_ABLevel_2()
        {
            return View();
        }
        public ActionResult DHQG_ABLevel_3()
        {
            return View();
        }
        public ActionResult DHQG_ABLevel_4()
        {
            return View();
        }
        public ActionResult DHQG_CLevel()
        {
            return View();
        }
        public ActionResult DHQG_CLevel_2()
        {
            return View();
        }
        public ActionResult DHQG_CLevel_3()
        {
            return View();
        }
        public ActionResult DHQG_CLevel_4()
        {
            return View();
        }
        // GUI cấp cơ sở 
        public ActionResult BasicLevel1_Coso()
        {
            return View();
        }
        public ActionResult BasicLevel2_Coso()
        {
            return View();
        }
        public ActionResult BasicLevel3_Coso()
        {
            return View();
        }
        public ActionResult BasicLevel4_Coso()
        {
            return View();
        }
        public ActionResult BasicLevel5_Coso()
        {
            return View();
        }
    }
}

QLDETAI_11_2/QLDETAI/Views/Guide/BasicLevel.cshtml
@{
    ViewBag.Title = "BasicLevel";
}

<link href="~/Content/jquery-ui.css" rel="stylesheet" />
<script src="~/Scripts/jquery-1.9.1.js"></script>
<script src="~/Scripts/js-func-nav.js"></script>
<script src="~/Scripts/jquery-ui.js"></script>

<script>
    $(function () { $("#tabs").tabs(); });
</script>
<div class="col">
    <h2>Cấp cơ sở</h2>
    <h3>Giới thiệu</h3>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer dictum, neque ut imperdiet pellentesque, nulla tellus tempus magna, sed consectetur orci metus a justo. Aliquam ac congue nunc. Mauris a tortor ut massa egestas tempus. Pellentesque tincidunt fermentum diam sagittis ullamcorper.</p>
    <h3>Gợi ý</h3>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer dictum, neque ut imperdiet pellentesque, nulla tellus tempus magna, sed consectetur orci metus a justo. Aliquam ac congue nunc. Mauris a tortor ut massa egestas tempus. Pellentesque tincidunt fermentum diam sagittis ullamcorper.</p>
</div>
<div class="col_2 last">
    <h2>Các bước đăng ký</h2>
    <div class="breadcrumb flat">
        <a href="@Url.Action("BasicLevel", "Guide")" class="active">Đề xuất</a>
        <a href="@Url.Action("BasicLevel_2", "Guide")">Compare</a>
        <a href="@Url.Action("BasicLevel_3", "Guide")">Order Confirmation</a>
        <a href="@Url.Action("BasicLevel_4", "Guide")">Checkout</a>
    </div>
    <br />
    <br />
    <div id="tabs">
        <ul>
            <li><a href="#tabs-1">Tab One</a></li>
            <li><a href="#tabs-2">Tab Two</a></li>
            <li><a href="#tabs-3">Tab Three</a></li>
        </ul>
        <div id="tabs-1">
            <p>Tab One Content Here.</p>
        </div>
        <div id="tabs-2">
            <p>Tab Two Contents Here</p>
        </div>
        <div id="tabs-3">
            <p>Tab Three Contents Here.</p>
        </div>
    </div>
</div>
<div class="cl">&nbsp;</div>

QLDETAI_11_2/QLDETAI/Views/Guide/BasicLevel1_Coso.cshtml
@{
    ViewBag.Title = "BasicLevel";
}

<link href="~/Content/jquery-ui.css" rel="stylesheet" />
<link href="~/Content/site.capcoso.css" rel="stylesheet" />
<script src="~/Scripts/jquery-1.9.1.js"></script>
<script src="~/Scripts/js-func-nav.js"></script>
<script src="~/Scripts/jquery-ui.js"></script>

<script>
    $(function () { $("#tabs").tabs(); });
</script>
<div class="col">
    <h2>Cấp cơ sở</h2>
    <h3>Giới thiệu</h3>
    <p>Đây là đề tài mang cấp cơ sở gồm có 2 bộ phận tham gia là cá, nhân tổ chức(người đăng ký) và cơ quan hành chính nhà nước( người đánh giá đề tài) thông qua 5 quy trình: đăng ký, thuyết minh,nghiệm thu,giám định và triển khai đề tài </p>
    <h3>Gợi ý</h3>
    <p>Quy trình thực hiện đề tài nghiên khoa học cấp cơ sở trải qua 5 bước trong đó chủ nhiệm đề tài là người đại diện đối tượng nghiên cứu thực hiện các quy trình nhận và nộp các biểu mẫu yêu cầu ...</p>
</div>
<div class="col_2 last">
    <h2>Các bước đăng ký</h2>
    <div class="breadcrumb flat">
        <a href="@Url.Action("BasicLevel1_Coso", "Guide")" class="active">Đăng ký sơ tuyển</a>
        <a href="@Url.Action("BasicLevel2_Coso", "Guide")">Thuyết minh</a>
        <a href="@Url.Action("BasicLevel3_Coso", "Guide")">Ký hợp đồng và giám định</a>
        <a href="@Url.Action("BasicLevel4_Coso", "Guide")">Nghiệm thu</a>
        <a href="@Url.Action("BasicLevel5_Coso", "Guide")">Triển khai đề tài</a>
    </div>
    <br />
    <br />
    <div id="tabs" style="width:600px;height:auto;overflow:auto;">
        <ul>
            <li><a href="#tabs-1">Bước 1</a></li>
            <li><a href="#tabs-2">Bước 2</a></li>
            <li><a href="#tabs-3">Bước 3</a></li>
            <li><a href="#tabs-4">Bước 4</a></li>
  
        </ul>
            
        <div id="tabs-1">
            <p><h4 class="h4_dangky">BƯỚC 1</h4></p>
            <p>Người đăng ký đề tài tiến hành điền vào mẫu đăng ký đề tài theo mẫu sau
                .</p><br />
            <p>
                <h4 class="h4_dangky">CÁC BIỂU MẪU LIÊN QUAN</h4>
                <a href="~/File/Phieudangkysotuyen.doc" class="bieumau" style="color: blue;">Phiếu đăng ký đề tài sơ tuyển</a>
            </p>
        </div>
        <div id="tabs-2">
            <p><h4 class="h4_dangky">BƯỚC 2</h4></p>
            <p>Người đăng ký đề tài tiến hành điền vào mẫu tóm tắt hoạt động KHCN của cơ quản chủ trì đề tài theo mẫu sau</p><br />
            <p>
                <h4 class="h4_dangky">CÁC BIỂU MẪU LIÊN QUAN</h4>
            <a href="~/File/Cap So KHCN/Tom tat hoat dong NCKH cua to chuc chu tri de tai.doc" class="bieumau" style="color: blue;">Phiếu tóm tắt hoạt động KHCN của cơ quan chủ trì đề tài</a>
            </p>
         </div>
         <div id="tabs-3">
            <p><h4 class="h4_dangky">BƯỚC 3</h4></p>
            <p>Người đăng ký tiến hành thêm thành viên và chọn chủ trì đề tài theo mẫu sau</p>
        </div>`
          <div id="tabs-4">
            <p><h4 class="h4_dangky">BƯỚC 4</h4></p>
            <p>Người đăng ký đề tài tiến hành điền vào mẫu tóm tắt hoạt động KHCN của cơ quản chủ trì đề tài theo mẫu sau</p><br />
             <p>
                <h4 class="h4_dangky">CÁC BIỂU MẪU LIÊN QUAN</h4>
              <a href="~/File/Cap So KHCN/Ly lich nha khoa hoc.doc" class="bieumau" style="color: blue;">Phiếu lý lịch khoa học</a>
            </p>
          </div>
    </div>
</div>
<div class="cl">&nbsp;</div>

QLDETAI_11_2/QLDETAI/Views/Guide/BasicLevel2_Coso.cshtml
@{
    ViewBag.Title = "BasicLevel";
}

<link href="~/Content/jquery-ui.css" rel="stylesheet" />
<link href="~/Content/site.capcoso.css" rel="stylesheet" />
<script src="~/Scripts/jquery-1.9.1.js"></script>
<script src="~/Scripts/js-func-nav.js"></script>
<script src="~/Scripts/jquery-ui.js"></script>

<script>
    $(function () { $("#tabs").tabs(); });
</script>
<div class="col">
    <h2>Cấp cơ sở</h2>
     <h3>Giới thiệu</h3>
    <p>Đây là đề tài mang cấp cơ sở gồm có 2 bộ phận tham gia là cá, nhân tổ chức(người đăng ký) và cơ quan hành chính nhà nước( người đánh giá đề tài) thông qua 5 quy trình: đăng ký, thuyết minh,nghiệm thu,giám định và triển khai đề tài </p>
    <h3>Gợi ý</h3>
    <p>Quy trình thực hiện đề tài nghiên khoa học cấp cơ sở trải qua 5 bước trong đó chủ nhiệm đề tài là người đại diện đối tượng nghiên cứu thực hiện các quy trình nhận và nộp các biểu mẫu yêu cầu ...</p>
</div>
<div class="col_2 last">
    <h2>Các bước đăng ký</h2>
    <div class="breadcrumb flat">
        <a href="@Url.Action("BasicLevel1_Coso", "Guide")">Đăng ký sơ tuyển</a>
        <a href="@Url.Action("BasicLevel2_Coso", "Guide")" class="active">Thuyết minh</a>
        <a href="@Url.Action("BasicLevel3_Coso", "Guide")">Ký hợp đồng và giám định</a>
        <a href="@Url.Action("BasicLevel4_Coso", "Guide")">Nghiệm thu</a>
        <a href="@Url.Action("BasicLevel5_Coso", "Guide")">Triển khai đề tài</a>
    </div>
    <br />
    <br />
    <div id="tabs" style="width:600px;height:auto;overflow:auto;">
        <ul>
            <li><a href="#tabs-1">Bước 1</a></li>
            <li><a href="#tabs-2">Bước 2</a></li>
            <li><a href="#tabs-3">Bước 3</a></li>
        </ul>
        <div id="tabs-1">
            <p><h4 class="h4_dangky">BƯỚC 1</h4></p>
            <p>Chuyên viên hướng dẫn thủ tục và gởi các mẫu thuyết minh đề tài, lý lịch khoa học của chủ nhiệm đề tài, lý lịch khoa học của cộng tác viên chính(Thời gian thực hiện tối đa 1 ngày).</p><br />
            <br />
            <p>
                <h4 class="h4_dangky">CÁC BIỂU MẪU LIÊN QUAN</h4>
                <a href="~/File/Thuyetminhdetainghiencuu.doc"  class ="bieumau" style="color: blue;>Thuyết minh đế tài</a><br />
                <a href="~/File/Lylichkhoahoc.doc"  class ="bieumau" style="color: blue";>Lý lịch khoa học</a>
            </p>
        </div>
        <div id="tabs-2">
            <p><h4 class="h4_dangky">BƯỚC 2</h4></p>
            <p>Chuyên viên chịu trách xét duyệt đề tài và trình lãnh đạo Sở phê duyệt.</p>
        </div>
        <div id="tabs-3">
            <p><h4 class="h4_dangky">BƯỚC 3</h4></p>
            <p>Hội đồng khoa học và chuyên viên chịu trách nhiệm xem xét đánh giá toàn bộ mục tiêu, nội dung, phương pháp nghiên cứu, sản phẩm và chấm điểm đề tài. Chuyên viên tổng hợp và công bố kết quả (Thời gian thực hiện 1 ngày)</p>
        </div>
    </div>
</div>
<div class="cl">&nbsp;</div>

QLDETAI_11_2/QLDETAI/Views/Guide/BasicLevel3_Coso.cshtml
@{
    ViewBag.Title = "BasicLevel";
}

<link href="~/Content/jquery-ui.css" rel="stylesheet" />
<link href="~/Content/site.capcoso.css" rel="stylesheet" />
<script src="~/Scripts/jquery-1.9.1.js"></script>
<script src="~/Scripts/js-func-nav.js"></script>
<script src="~/Scripts/jquery-ui.js"></script>

<script>
    $(function () { $("#tabs").tabs(); });
</script>
<div class="col">
    <h2>Cấp cơ sở</h2>
    <h3>Giới thiệu</h3>
    <p>Đây là đề tài mang cấp cơ sở gồm có 2 bộ phận tham gia là cá, nhân tổ chức(người đăng ký) và cơ quan hành chính nhà nước( người đánh giá đề tài) thông qua 5 quy trình: đăng ký, thuyết minh,nghiệm thu,giám định và triển khai đề tài </p>
    <h3>Gợi ý</h3>
    <p>Quy trình thực hiện đề tài nghiên khoa học cấp cơ sở trải qua 5 bước trong đó chủ nhiệm đề tài là người đại diện đối tượng nghiên cứu thực hiện các quy trình nhận và nộp các biểu mẫu yêu cầu ...</p>
</div>
<div class="col_2 last">
    <h2>Các bước đăng ký</h2>
    <div class="breadcrumb flat">
        <a href="@Url.Action("BasicLevel1_Coso", "Guide")">Đăng ký sơ tuyển</a>
        <a href="@Url.Action("BasicLevel2_Coso", "Guide")">Thuyết minh</a>
        <a href="@Url.Action("BasicLevel3_Coso", "Guide")"  class="active">Ký hợp đồng và giám định</a>
        <a href="@Url.Action("BasicLevel4_Coso", "Guide")">Nghiệm thu</a>
        <a href="@Url.Action("BasicLevel5_Coso", "Guide")">Triển khai đề tài</a>
    </div>
    <br />
    <br />
    <div id="tabs">
        <ul>
            <li><a href="#tabs-1">Bước 1</a></li>
            <li><a href="#tabs-2">Bước 2</a></li>
            <li><a href="#tabs-3">Bước 3</a></li>
        </ul>
           <div id="tabs-1">

            <p><h4 class="h4_dangky">BƯỚC 1</h4></p>
            <p>Chuyên viên hướng dẫn chủ nhiệm đề tài lập Hợp đồng nghiên cứu khoa học và phát triển công nghệ lãnh đạo Sở phê duyệt
                (Thời gian tối đa 30 ngày kể từ ngày cấp kinh phí)
                .</p>
            <br />
             <p>
                <h4 class="h4_dangky">CÁC BIỂU MẪU LIÊN QUAN</h4>
                <a href="~/File/Dexuatkyhopdong.doc" class="bieumau" style="color: blue;">Mẫu đề xuất ký hợp đồng</a><br />
                <a href="~/File/Decuongcapkinhphi.doc" class="bieumau" style="color: blue;">Mẫu đề cương cấp kinh phí</a><br />
                <a href="~/File/Giấy đề nghị nộp quản lý phí.doc" class="bieumau" style="color: blue;">Giấy đề nghị nộp quản lý phí</a><br />
                <a href="~/File/Dutoankinhphi.xls" class="bieumau" style="color: blue;">Dự toán kinh phí</a>
            </p>
        </div>
          <div id="tabs-2">
            <p><h4 class="h4_dangky">BƯỚC 2</h4></p>
            <p>Sau khi chủ nhiệm đề tài nộp báo cáo tiến độ giai đoạn 1, chuyên viên chuẩn bị thủ tục tiến hành giám định đề tài, trình lãnh đạo Sở phê duyệt (Thời gian thực hiện tối đa 30 ngày)</p>
            <p>
        </div>
          <div id="tabs-3">
            <p><h4 class="h4_dangky">BƯỚC 3</h4></p>
             <p>Chuyên viên trực tiếp lập phiếu xử lý giám định trình lãnh đạo Sở phê duyệt
                 (Thời gian thực hiện tối đa 9 ngày kể từ khi nhận được báo cáo chỉnh sửa của chủ nhiệm đề tài).
             </p>
        </div>
        
    </div>
</div>
<div class="cl">&nbsp;</div>

QLDETAI_11_2/QLDETAI/Views/Guide/BasicLevel_2.cshtml
@{
    ViewBag.Title = "BasicLevel_2";
}
<link href="~/Content/jquery-ui.css" rel="stylesheet" />
<script src="~/Scripts/jquery-1.9.1.js"></script>
<script src="~/Scripts/js-func-nav.js"></script>
<script src="~/Scripts/jquery-ui.js"></script>
<script>
    $(function () { $("#tabs").tabs(); });
</script>
<div class="col">
    <h2>Cấp cơ sở</h2>
    <h3>Giới thiệu</h3>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer dictum, neque ut imperdiet pellentesque, nulla tellus tempus magna, sed consectetur orci metus a justo. Aliquam ac congue nunc. Mauris a tortor ut massa egestas tempus. Pellentesque tincidunt fermentum diam sagittis ullamcorper.</p>
    <h3>Gợi ý</h3>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer dictum, neque ut imperdiet pellentesque, nulla tellus tempus magna, sed consectetur orci metus a justo. Aliquam ac congue nunc. Mauris a tortor ut massa egestas tempus. Pellentesque tincidunt fermentum diam sagittis ullamcorper.</p>
</div>
<div class="col_2 last">
    <h2>Các bước đăng ký</h2>
    <div class="breadcrumb flat">
        <a href="@Url.Action("BasicLevel", "Guide")">Đề xuất</a>
        <a href="@Url.Action("BasicLevel_2", "Guide")" class="active">Compare</a>
        <a href="@Url.Action("BasicLevel_3", "Guide")">Order Confirmation</a>
        <a href="@Url.Action("BasicLevel_4", "Guide")">Checkout</a>
    </div>
    <br />
    <br />
    <div id="tabs">
        <ul>
            <li><a href="#tabs-1">Tab One</a></li>
            <li><a href="#tabs-2">Tab Two</a></li>
            <li><a href="#tabs-3">Tab Three</a></li>
        </ul>
        <div id="tabs-1">
            <p>Tab One Content Here.</p>
        </div>
        <div id="tabs-2">
            <p>Tab Two Contents Here</p>
        </div>
        <div id="tabs-3">
            <p>Tab Three Contents Here.</p>
        </div>
    </div>
</div>
<div class="cl">&nbsp;</div>

QLDETAI_11_2/QLDETAI/Views/Guide/BasicLevel_3.cshtml
@{
    ViewBag.Title = "BasicLevel_3";
}
<link href="~/Content/jquery-ui.css" rel="stylesheet" />
<script src="~/Scripts/jquery-1.9.1.js"></script>
<script src="~/Scripts/js-func-nav.js"></script>
<script src="~/Scripts/jquery-ui.js"></script>
<script>
    $(function () { $("#tabs").tabs(); });
</script>
<div class="col">
    <h2>Cấp cơ sở</h2>
    <h3>Giới thiệu</h3>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer dictum, neque ut imperdiet pellentesque, nulla tellus tempus magna, sed consectetur orci metus a justo. Aliquam ac congue nunc. Mauris a tortor ut massa egestas tempus. Pellentesque tincidunt fermentum diam sagittis ullamcorper.</p>
    <h3>Gợi ý</h3>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer dictum, neque ut imperdiet pellentesque, nulla tellus tempus magna, sed consectetur orci metus a justo. Aliquam ac congue nunc. Mauris a tortor ut massa egestas tempus. Pellentesque tincidunt fermentum diam sagittis ullamcorper.</p>
</div>
<div class="col_2 last">
    <h2>Các bước đăng ký</h2>
    <div class="breadcrumb flat">
        <a href="@Url.Action("BasicLevel", "Guide")">Đề xuất</a>
        <a href="@Url.Action("BasicLevel_2", "Guide")">Compare</a>
        <a href="@Url.Action("BasicLevel_3", "Guide")" class="active">Order Confirmation</a>
        <a href="@Url.Action("BasicLevel_4", "Guide")">Checkout</a>
    </div>
    <br />
    <br />
    <div id="tabs">
        <ul>
            <li><a href="#tabs-1">Tab One</a></li>
            <li><a href="#tabs-2">Tab Two</a></li>
            <li><a href="#tabs-3">Tab Three</a></li>
        </ul>
        <div id="tabs-1">
            <p>Tab One Content Here.</p>
        </div>
        <div id="tabs-2">
            <p>Tab Two Contents Here</p>
        </div>
        <div id="tabs-3">
            <p>Tab Three Contents Here.</p>
        </div>
    </div>
</div>
<div class="cl">&nbsp;</div>

QLDETAI_11_2/QLDETAI/Views/Guide/BasicLevel_4.cshtml
@{
    ViewBag.Title = "BasicLevel_4";
}
<link href="~/Content/jquery-ui.css" rel="stylesheet" />
<script src="~/Scripts/jquery-1.9.1.js"></script>
<script src="~/Scripts/js-func-nav.js"></script>
<script src="~/Scripts/jquery-ui.js"></script>
<script>
    $(function () { $("#tabs").tabs(); });
</script>
<div class="col">
    <h2>Cấp cơ sở</h2>
    <h3>Giới thiệu</h3>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer dictum, neque ut imperdiet pellentesque, nulla tellus tempus magna, sed consectetur orci metus a justo. Aliquam ac congue nunc. Mauris a tortor ut massa egestas tempus. Pellentesque tincidunt fermentum diam sagittis ullamcorper.</p>
    <h3>Gợi ý</h3>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer dictum, neque ut imperdiet pellentesque, nulla tellus tempus magna, sed consectetur orci metus a justo. Aliquam ac congue nunc. Mauris a tortor ut massa egestas tempus. Pellentesque tincidunt fermentum diam sagittis ullamcorper.</p>
</div>
<div class="col_2 last">
    <h2>Các bước đăng ký</h2>
    <div class="breadcrumb flat">
        <a href="@Url.Action("BasicLevel", "Guide")">Đề xuất</a>
        <a href="@Url.Action("BasicLevel_2", "Guide")">Compare</a>
        <a href="@Url.Action("BasicLevel_3", "Guide")">Order Confirmation</a>
        <a href="@Url.Action("BasicLevel_4", "Guide")"  class="active">Checkout</a>
    </div>
    <br />
    <br />
    <div id="tabs">
        <ul>
            <li><a href="#tabs-1">Tab One</a></li>
            <li><a href="#tabs-2">Tab Two</a></li>
            <li><a href="#tabs-3">Tab Three</a></li>
        </ul>
        <div id="tabs-1">
            <p>Tab One Content Here.</p>
        </div>
        <div id="tabs-2">
            <p>Tab Two Contents Here</p>
        </div>
        <div id="tabs-3">
            <p>Tab Three Contents Here.</p>
        </div>
    </div>
</div>
<div class="cl">&nbsp;</div>

QLDETAI_11_2/QLDETAI/Views/Guide/CapTruong.cshtml
@{
    ViewBag.Title = "B1. Đăng ký";
}


<link href="~/Content/jquery-ui.css" rel="stylesheet" />
<link href="~/Content/site.captruong.css" rel="stylesheet" />
<script src="~/Scripts/jquery-1.9.1.js"></script>
<script src="~/Scripts/js-func-nav.js"></script>
<script src="~/Scripts/jquery-ui.js"></script>

<script>
    $(function () { $("#tabs").tabs(); });
</script>
<div class="col">
    <h2>Cấp trường</h2>
    <h3>Giới thiệu</h3>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer dictum, neque ut imperdiet pellentesque, nulla tellus tempus magna, sed consectetur orci metus a justo. Aliquam ac congue nunc. Mauris a tortor ut massa egestas tempus. Pellentesque tincidunt fermentum diam sagittis ullamcorper.</p>
    <h3>Gợi ý</h3>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer dictum, neque ut imperdiet pellentesque, nulla tellus tempus magna, sed consectetur orci metus a justo. Aliquam ac congue nunc. Mauris a tortor ut massa egestas tempus. Pellentesque tincidunt fermentum diam sagittis ullamcorper.</p>
</div>
<div class="col_2 last">
    <h2>Các bước đăng ký</h2>
    <div class="breadcrumb flat">
        <a href="@Url.Action("CapTruong", "Guide")" class="active">Đăng ký</a>
        <a href="@Url.Action("CapTruong_1", "Guide")">Đánh giá xét duyệt</a>
        <a href="@Url.Action("CapTruong_2", "Guide")">Tổ chức thực hiện</a>
        <a href="@Url.Action("CapTruong_3", "Guide")">Đánh giá nghiệm thu</a>
    </div>
    <br />
    <br />
    <div id="tabs" style="width:600px;height:auto;overflow:auto;">
        <ul>
            <li><a href="#tabs-1">Quy trình</a></li>          
        </ul>
        <div id="tabs-1">
            <p><h4 class="h4_dangky">CÁC BƯỚC THỰC HIỆN</h4><br /></p>
            <p>_ Dựa vào thông báo kế hoạch hàng năm của ĐHQG-HCM , Phòng KHCN ra thông báo gửi đến các đơn vị. Các đơn vị phổ biến đến cán bộ Thuyết minh đề tài đăng ký theo mẫu.</p><br />
            <p>_ Sau khi thỏa mãn các tiêu chuẩn, các chủ nhiêm đề tài gửi biểu mẫu đăng kí đề tài cho phòng KHCN.<p><br />
                <h4 class="h4_dangky">CÁC BIỂU MẪU LIÊN QUAN</h4><br />
                <a href="~/File/CapTruong/Thuyet minh de tai cap truong 2103.doc" class="bieumau">Phiếu đăng ký thuyết minh đề tài cấp trường</a>
            </p>
        </div>     
    </div>
</div>
<div class="cl">&nbsp;</div>